### ISSUE TITLE
[Mod Compatibility] loot tables aren't found when using some mods

### ISSUE THREAD

**Issue by InkDragon** [PersonTheCat/OreStoneVariants#113]
just like  it says it seems like all my ores are dropping as coal rather then their correct variant. If you need any more information please feel free to ask

**Comment by PersonTheCat** [comment]
Hey, thanks for reporting this! I've been actively working on this mod for a few days and can absolutely confirm that this is not an issue for me. 

Which version of the mod, MC, and Forge are you using? Are you using any other mods? Have you changed any of the presets!

**Comment by InkDragon** [comment]
Ore+Stone+Variants-5.10-1.16.2
Minecraft 1.16.4
Forge 35.1.37
No config changes
Modlist: [https://pastebin.com/XvxyMLpu](https://pastebin.com/XvxyMLpu)

I realize I am using a lot of mods, so it might be hard to pick up out the issue. I tested the ore dropping with both a non-enchanted vanilla Minecraft netherite pickaxe and my fully enchanted one from Gems & jewels and got the same results

**Comment by PersonTheCat** [comment]
I retested this and can definitely confirm this is not an issue with the regular configuration. I have made a lot of changes in the newer version and am nearing release. If you want, you can test this new build out and maybe some edge case will have been fixed.

[Ore Stone Variants-5.11-1.16.4-franklin.zip](https://github.com/PersonTheCat/ore_stone_variants/files/5868197/Ore.Stone.Variants-5.11-1.16.4-franklin.zip)

**Comment by PersonTheCat** [comment]
If you are still experiencing this issue with the new build, please try a clean environment with no other mods and let me know if it's still occurring. This will help me rule out if another mod is causing the issue. Thanks!

**Comment by InkDragon** [comment]
Still coal with the file you posted in my mod pack

in a clean environment its fine, ores drop as normal

**Comment by PersonTheCat** [comment]
This sounds like a mod compatibility Issue and not necessarily a bug. I would need to know which of these mods is causing the issue before I can figure out why it's happening.

**Comment by InkDragon** [comment]
Oh yep I just figured it out! [BasicNetherOres-1.16.4-5.4.0](https://www.curseforge.com/minecraft/mc-mods/basic-nether-ores) seems to be causing the issue as disabling it allowed me to once again acquire iron ore. would you like me to cross post the issue to their git?

**Comment by PersonTheCat** [comment]
You can, but I'm still not sure why this is happening. It might not be a bug with either mod, but rather just a compatibility issue.

**Comment by InkDragon** [comment]
okay I will leave it to you to figure that out and take action as needed. thank you for helping me out with this issue. Sorry for any trouble.

**Comment by PersonTheCat** [comment]
No problem! Thanks for your help! Feel

**Comment by Prophious** [comment]
i was getting the same issue, but i did not have BasicNetherOres in my modpack, however i did find something that another mod was causing the issue while waring an item, in artifacts there is a "lucky Scarf" that is suppose to give an extra level of fortune to mined blocks, with it on got coal for every ore placed by ore stone variant.... dont know if its just those mods or my modpack that i have put together, will investigate more, all versions of mods in question are up to date as of post

**Comment by InkDragon** [comment]
> 

> i was getting the same issue, but i did not have BasicNetherOres in my modpack, however i did find something that another mod was causing the issue while waring an item, in artifacts there is a "lucky Scarf" that is suppose to give an extra level of fortune to mined blocks, with it on got coal for every ore placed by ore stone variant.... dont know if its just those mods or my modpack that i have put together, will investigate more, all versions of mods in question are up to date as of post

i had that mod in my pack as well...

**Comment by PersonTheCat** [comment]
This is very helpful. I'll take a look at it as soon as I'm done with Cave Generator. I'm about 95% on that project at the moment, then I have a bug fix update planned for OSV 1.12, and then finally OSV 1.16. Shouldn't be too long now.

**Comment by InkDragon** [comment]
no worries and thank you for doing your best to fix this issue

**Comment by PersonTheCat** [comment]
I believe this issue has been resolved in 7.0. Everything is working for me. If you do give the update a try, please let me know if you encounter any issues.
