### ISSUE TITLE
[Feature Request?] Mod compatibility - Realistic Ore Veins

### ISSUE THREAD

**Issue by juraj-hrivnak** [PersonTheCat/OreStoneVariants#114]
- Like: ores generated with Realistic Ore Veins will be applying the stone variants that they were generated in.
`But that's maybe rather what Realistic Ore Veins should do?`

Thanks!

**Comment by PersonTheCat** [comment]
Thanks for the suggestion! I am currently working out how to generate ore variants in the shape a vein like this mod can do. Still need to do figure out how this will look in the presets and then how to actually do it. That's a couple updates out. Maybe 5.13 or 5.14.

**Comment by juraj-hrivnak** [comment]
Wow, that would be awesome! 
Were you thinking about adding indicators? (That's the only thing why I'm using Realistic Ore Veins)

**Comment by PersonTheCat** [comment]
That's a good idea. As soon as I get large clusters mode back in the 1.16 version, I'll consider it. The large clusters feature makes ore types spawn close together and far apart, so that would make sense.

**Comment by juraj-hrivnak** [comment]
Thanks for everything :D The last question: will you consider making the indicators also in 1.12? ...someday

**Comment by PersonTheCat** [comment]
I'll think about it, but most likely not. Just because I can't really work on the 1.16 version, look into porting Cave Generator to 1.16, and also put much time into the 1.12 version. It's a bit too much for me to support.

**Comment by juraj-hrivnak** [comment]
No problem with that. There is also school and real-life.  Also, 1.12 is being outdated more and more. It looks like 1.16 is the future.

**Comment by PersonTheCat** [comment]
I have added a few new generator types to 7.0 and will be adding more in the future, especially in the 1.18 version. Marking this issue as resolved.
