### ISSUE TITLE
Upgraded Netherite tools dropping coal and assets

### ISSUE THREAD

**Issue by TLGJustin307** [PersonTheCat/OreStoneVariants#124]
When mining any OSV ore with a golderite, corrupterite or ultimerite pickaxe instead of dropping the ore it drops coal. The maker of the Upgraded Netherite mod says this bug is on the OSV mod side. Here is a link to the issue someone else made at the Upgraded Netherite mod: https://www.curseforge.com/minecraft/mc-mods/upgraded-netherite/issues/10

Also I saw that someone already made an issue about the assets not loading well, I am really hoping that you could fix this bug for 1.16.5. I have been working on my modpack for quite some time and I think I can upload it in like 1-2 months. OSV is just one of the best additions to my modpack and I do not want to delete it, but having it crash for people that dont know they need to load it a second time is quite annoying.
https://github.com/PersonTheCat/ore_stone_variants/issues/122

I am really hoping you can do something with this because I just really love this mod!

**Comment by potatoplant64** [comment]
I wanted to make the same issues, is there a fix for this?

**Comment by PersonTheCat** [comment]
Not yet, but I am aware. Still not sure what causes the issue, but it is next on the list. Just finished the big Cave Generator update and am working on OSV 1.12 bug fixes first. Should just be a more days before I can begin working on 1.16 fixes.

**Comment by potatoplant64** [comment]
Thanks, really looking forward to the next update!
Good luck!

**Comment by ochotonida** [comment]
This issue also applies to Curios' fortune modifier (https://github.com/ochotonida/artifacts/issues/104). Curios uses a [global loot modifier](https://github.com/TheIllusiveC4/Curios/blob/1.16.x-forge/src/main/java/top/theillusivec4/curios/common/objects/FortuneBonusModifier.java) to re-generate the dropped loot with the modified fortune level. It seems the loot tables of the blocks in this mod always generate coal, causing this issue.

**Comment by PersonTheCat** [comment]
Yeah. For the most part, any mod that tries to manipulate drops and other block properties is incompatible with OSV at a design level because then both mods are doing the exact same thing. 
I can try to look at this, but it's gonna be awhile because I'm super backed up at the moment with other features to implement first. Feel free to join the Discord server for more updates.

**Comment by ochotonida** [comment]
I assume you're generating drops dynamically and simply ignoring the result of the loot table? You can probably fix these issues by using a custom loot pool entry type instead.

**Comment by PersonTheCat** [comment]
Yep. It's just a lot of work to change. We're pulling loot from other blocks and dynamically substituting items otf. There's a ton of data generation in this mod and I'd really prefer to avoid adding more. I may not have a choice if I want to support other mods, it's just that, again, OSV provides a ton of options for customizing loot and other block parameters. It doesn't really make sense to use other mods that do the same thing alongside OSV. 
I don't know. Maybe this case is a little different. I'll put some thought into it.

**Comment by PersonTheCat** [comment]
OSV 7.0 now uses a passthrough by default to handle drops. This means by default, you only have to modify the drops of the original ore to change the variants' drops. Everything is working for me. Please give the update a try and let me know if you're still having any issues.
