### ISSUE TITLE
Missing Textures

### ISSUE THREAD

**Issue by fleetag** [PersonTheCat/OreStoneVariants#131]
I'm testing out a Vanilla-esque modpack on CurseForge when I stumbled upon missing ore textures for coal, I'm not sure if this effects all ores on all stones.

![2021-08-20_09 03 10](https://user-images.githubusercontent.com/70476620/130252897-d943a96f-4599-4b61-af8c-7f63478f42e1.png)

I'm currently using Forge 1.16.5 version 36.2.0 and Ore_Stone_Variants-6.2.jar

**Comment by PersonTheCat** [comment]
Give me as many details as you can. I don't have this issue. Also try running the mod with no other mods just to see if maybe some other mod is interfering. And finally, make sure to check the generated resources folder (`config/osv/resources`) and see if the textures are either not generating at all or just not loading.

**Comment by fleetag** [comment]
Here's a list of mods I'm using for my recent pack update: [Quark+ testing.zip](https://github.com/PersonTheCat/ore_stone_variants/files/7023665/Quark%2B.testing.zip)

- Quark
- Charm Reforged
- Configured
- Forgery

- Console Experience
- Animated Recipe Book
- V-Tweaks
- Vanilla Tweaks

- Upgrade Aquatic
- Savage & Ravage
- Berry Good
- Buzzier Bees
- YUNG's Better Caves (Forge)
- YUNG's Better Mineshafts (Forge)

- Abundance
- Bayou Blues
- Better Badlands
- Betterlands
- Enhanced Mushrooms (Forge)
- Environmental

- Better Spawn Control
- Well-Behaved Mobs
- Smarter HUD
- Gui Clock
- Gui Compass
- Extra Boats

**Comment by PersonTheCat** [comment]
Have you tried running OSV with no other mods? Have any assets generated inside of `config/osv/resources`?

**Comment by fleetag** [comment]
I ran OSV without any mods that change world generation, and checked that there were no new assets inside of config/osv/resources with no problems. I turned all the mods I was using back on, and it turned out to be working properly. It turned out the missing texture was a vanilla coal ore block. I'm not sure how that happened, but I think I just needed to repair my modpack's profile over on CurseForge's app.
![2021-08-20_09 03 10](https://user-images.githubusercontent.com/70476620/131263508-cd5cec11-25c0-4fff-bc43-a6ddf3d045b5.png)
![2021-08-29_15 18 51](https://user-images.githubusercontent.com/70476620/131263483-820636d6-666e-4882-8033-d25c15ac4118.png)

**Comment by PersonTheCat** [comment]
Huh. That's really strange. Definitely let me know if it happens again.

**Comment by fleetag** [comment]
Ok I will.

Stupid question, but will OSV be made compatible with blackgear27's Caves & Cliffs Backport mod for people who want to use the 1.17 textures for 1.16.5?

**Comment by PersonTheCat** [comment]
You should be able to just enable `overlaysFromRp` in the client config and regenerate your textures for that. They probably won't look as good, though, because the algorithm is designed for the 1.12 style textures. Unfortunately, texture generation is pretty much the most complex part of this mod.

**Comment by fleetag** [comment]
Thanks, I'm looking forward to see you progress your mod to 1.17+ along with the other mods I'm using for my modpack.

**Comment by PersonTheCat** [comment]
I'm closing this issue since the texture handling was written from scratch once again. I believe this issue no longer applies. If it does, please let me know, but there's likely not much else I can do.
