### ISSUE TITLE
Add an option to disable Background Imitation for specific ores

### ISSUE THREAD

**Issue by RecyclingTiger** [PersonTheCat/OreStoneVariants#134]
Currently when Background Imitation is enabled, nether ores are forced to use the netherrack sound rather than the ore's sound effect. For example this prevents nether quartz ore variants from playing their vanilla quartz ore sound. However, disabling Background Imitation would prevent other ores from imitating properties from multiple background blocks, like if you want an ore to spawn in both stone & wood and have the respective sound effects.
Since soundType gets ignored when Background Imitation is enabled, I am unable to change the sound of the ore back to the nether quartz ore sound effect.

**Comment by PersonTheCat** [comment]
This is not a bug, but I will consider coercing properties even when this feature is enabled at some point in the future.

**Comment by PersonTheCat** [comment]
This will be added in 7.0. It's a very large update since we're rebuilding on top of CatLib, so it may take a least a few more weeks.

**Comment by PersonTheCat** [comment]
This feature was added in 7.0. Just set `variant.bgImitation: false` inside of any preset to fine tune it. Marking this issue as resolved.
