### ISSUE TITLE
Soapstone ore backgrounds from byg appears gray with the default configs

### ISSUE THREAD

**Issue by RecyclingTiger** [PersonTheCat/OreStoneVariants#137]
In osv version 7.0, ores that have soapstone backgrounds from oh the biomes you go are discolored gray instead of black like the actual block.

![soapstone_ores](https://user-images.githubusercontent.com/89662661/145897602-ba052161-aa52-4e97-b12f-e6815136ce4b.png)

**Comment by PersonTheCat** [comment]
Looks like this is just a biome colors issue. I'll do a small bug fix update including this in a week or two.

**Comment by PersonTheCat** [comment]
Hey, just wanted to give an update on this issue. I basically have not been able to figure out where the color comes from for these blocks or why it only works for the overlay models. As far as I can tell, these blocks do not have biome colors, nor do they contain a tint index at all. And I'm not aware of any colorizers in code whatsoever from BYG, so I'm not sure how to replicate it. 

Sorry for the delay, but I'm pretty much completely blocked on this issue.

**Comment by RecyclingTiger** [comment]
Okay I found out this seems to be an issue with byg's soapstone texture file, not osv.
A way to get around it is by creating a new image with the soapstone texture (not copy and pasting the original one) which doesn't cause this problem to happen.

**Comment by PersonTheCat** [comment]
Hey, @RecyclingTiger thanks for your help on this and sorry for the delays. I'll reach out to @CorgiTaco and see if they're alright with me just including the texture.
