### ISSUE TITLE
Compatibility with Chipped, Chisel, and Similar Mods [1.16.5]

### ISSUE THREAD

**Issue by FluxedU** [PersonTheCat/OreStoneVariants#138]
Crash happens when i try to load the game with OSV-forge installed
[crash-2021-12-18_23.04.03-client.txt](https://github.com/PersonTheCat/OreStoneVariants/files/7740223/crash-2021-12-18_23.04.03-client.txt)

Removing the mod fixes the problem

**Comment by PersonTheCat** [comment]
This is technically a duplicate, but a proper ticket was never opened for the issue. See #130. This issue is a mod compatibility issue with Chipped and Chisel. I'll look at it later.

**Comment by PersonTheCat** [comment]
Hey, @FluxedU and @Stormalisk. Is there any way you can retest this issue with OSV 7.1? I switched back to the old behavior from 6.2, so it should work again, but the problem never occurred for me at all, so I can't test it myself.

**Comment by FluxedU** [comment]
Fixed and working flawless, thank you
