### ISSUE TITLE
Some textures aren't supported

### ISSUE THREAD

**Issue by m0bz73r** [PersonTheCat/OreStoneVariants#144]
![Screenshot (17)](https://user-images.githubusercontent.com/14284060/147861708-0f679db5-627d-4619-85ad-ee79208b636d.png)
Not sure if this is the right place to post this issue, but I don't know where else to go. My block textures work, but this one specifically doesn't work for item textures. It (deepslate) is also the only background block I have added to the background block list. Minecraft version 1.16.5 with V 7.4 OSV.

**Comment by PersonTheCat** [comment]
Yeah, sorry. Asset generation is extremely complicated. OSV basically operates directly on the draw JSON and PNG files to produce its assets before everything normally gets loaded. These models have a lot of edge cases, and so there will always be assets that just aren't supported.

I'll look into these specific models after a short break from OSV (have been working on data gen only for several weeks). In the meantime, if this is for a mod pack, you can just create these models manually. Feel free to join the Discord server for help setting that up, if needed. They're basically just regular model files.

Hope this helps!

**Comment by m0bz73r** [comment]
I would love to join the discord to get some help, but I have no idea where to join lol. Thank you for the response, regardless.

**Comment by PersonTheCat** [comment]
Sorry about that. Here you go. https://discord.gg/UNsXfvA

**Comment by frank89722** [comment]
Because there are a lot of ores in my mod pack so I wrote a simple python script to fix this temporarily.

Just put it in the `/config/osv/models/item` and run. It'll generate missing item models for your quark deepslate ores
https://gist.github.com/frank89722/101e869ea7ce695e746e100fe7f6e574

**Comment by PersonTheCat** [comment]
Hey, I made some changes to fix a few of these item models (especially for Quark deepslate). I believe this issue is resolved, but do let me know if you try the latest version (7.5+) and still have any issues.
