### ISSUE TITLE
[1.12.2]Crash

### ISSUE THREAD

**Issue by BraveCaperCat** [PersonTheCat/OreStoneVariants#155]
Exit Code: -1
Crash Log: [latest.log](https://github.com/PersonTheCat/OreStoneVariants/files/8224107/latest.log)
Caused by: java.io.FileNotFoundException: C:\Users\<private info>\curseforge\minecraft\Instances\Crashed In Space Modpack\config\osv\osv_4551888657586847577.zip (The process cannot access the file because it is being used by another process)
The computer restarted last night (GMT) so nothing is running
mod list:
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                       | Version           | Source                                          | Signature                                |
	|:----- |:------------------------ |:----------------- |:----------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft                | 1.12.2            | minecraft.jar                                   | None                                     |
	| LCH   | mcp                      | 9.42              | minecraft.jar                                   | None                                     |
	| LCH   | FML                      | 8.0.99.99         | forge-1.12.2-14.23.5.2860.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                    | 14.23.5.2860      | forge-1.12.2-14.23.5.2860.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | advancedrocketrycore     | 1                 | minecraft.jar                                   | None                                     |
	| LCH   | crafttweaker             | 4.1.20            | CraftTweaker2-1.12-4.1.20.674.jar               | None                                     |
	| LCH   | jei                      | 4.16.1.301        | jei_1.12.2-4.16.1.301.jar                       | None                                     |
	| LCH   | ctm                      | MC1.12.2-1.0.2.31 | CTM-MC1.12.2-1.0.2.31.jar                       | None                                     |
	| LCH   | chisel                   | MC1.12.2-1.0.2.45 | Chisel-MC1.12.2-1.0.2.45.jar                    | None                                     |
	| LCH   | mantle                   | 1.12-1.3.3.55     | Mantle-1.12-1.3.3.55.jar                        | None                                     |
	| LCH   | tconstruct               | 1.12.2-2.13.0.183 | TConstruct-1.12.2-2.13.0.183.jar                | None                                     |
	| LCH   | immersiveengineering     | 0.12-98           | ImmersiveEngineering-0.12-98.jar                | None                                     |
	| LCH   | libvulpes                | 0.4.2.-88         | LibVulpes-1.12.2-0.4.2-88-universal.jar         | None                                     |
	| LCH   | advancedrocketry         | 1.7.0.-232        | AdvancedRocketry-1.12.2-1.7.0-232-universal.jar | None                                     |
	| LCH   | cxlibrary                | 1.6.1             | cxlibrary-1.12.1-1.6.1.jar                      | None                                     |
	| LCH   | advinv                   | 1.4.2             | advInv-1.12.1-1.4.2.jar                         | None                                     |
	| LCH   | mtlib                    | 3.0.7             | MTLib-3.0.7.jar                                 | None                                     |
	| LCH   | art                      | 1.0.0             | ARTweaker-1.12.2-1.0.0.jar                      | None                                     |
	| LCH   | baubles                  | 1.5.2             | Baubles-1.12-1.5.2.jar                          | None                                     |
	| LCH   | buildcraftlib            | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                    | None                                     |
	| LCH   | forgelin                 | 1.8.4             | Forgelin-1.8.4.jar                              | None                                     |
	| LCH   | bcoreprocessing          | 1                 | bc-ore-processing-7.99.24.4-1.jar               | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | betterquesting           | 3.5.329           | BetterQuesting-3.5.329.jar                      | None                                     |
	| LCH   | bookshelf                | 2.3.590           | Bookshelf-1.12.2-2.3.590.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | gamestages               | 2.0.123           | GameStages-1.12.2-2.0.123.jar                   | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | bq_gs                    | 1.0.0             | BQ_Gamestages-1.0.0.jar                         | None                                     |
	| LCH   | bq_msi                   | 1.0.7             | BQ_Multiblock_Structure_Integration-1.0.7.jar   | None                                     |
	| LCH   | buildcraftcore           | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                    | None                                     |
	| LCH   | buildcraftbuilders       | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                    | None                                     |
	| LCH   | buildcrafttransport      | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                    | None                                     |
	| LCH   | buildcraftsilicon        | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                    | None                                     |
	| LCH   | buildcraftcompat         | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                    | None                                     |
	| LCH   | buildcraftenergy         | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                    | None                                     |
	| LCH   | buildcraftfactory        | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                    | None                                     |
	| LCH   | buildcraftrobotics       | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                    | None                                     |
	| LCH   | chiselsandbits           | 14.33             | chiselsandbits-14.33.jar                        | None                                     |
	| LCH   | connectedglass           | 1.1.1             | connectedglass-1.1.1-mc1.12.jar                 | None                                     |
	| LCH   | controlling              | 3.0.10            | Controlling-3.0.10.jar                          | None                                     |
	| LCH   | ctgui                    | 1.0.0             | CraftTweaker2-1.12-4.1.20.674.jar               | None                                     |
	| LCH   | crafttweakerjei          | 2.0.3             | CraftTweaker2-1.12-4.1.20.674.jar               | None                                     |
	| LCH   | cucumber                 | 1.1.3             | Cucumber-1.12.2-1.1.3.jar                       | None                                     |
	| LCH   | forgeendertech           | 1.12.2-4.5.6.0    | ForgeEndertech-1.12.2-4.5.6.0-build.0619.jar    | None                                     |
	| LCH   | waila                    | 1.8.26            | Hwyla-1.8.26-B41_1.12.2.jar                     | None                                     |
	| LCH   | ironbackpacks            | 1.12.2-3.0.8-12   | IronBackpacks-1.12.2-3.0.8-12.jar               | None                                     |
	| LCH   | ironchest                | 1.12.2-7.0.67.844 | ironchest-1.12.2-7.0.72.847.jar                 | None                                     |
	| LCH   | ironfurnaces             | 1.3.5             | ironfurnaces-1.3.5.jar                          | None                                     |
	| LCH   | ironjetpacks             | 1.1.0             | IronJetpacks-1.12-2-1.1.0.jar                   | None                                     |
	| LCH   | itemstages               | 2.0.49            | ItemStages-1.12.2-2.0.49.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | jeresources              | 0.9.2.60          | JustEnoughResources-1.12.2-0.9.2.60.jar         | None                                     |
	| LCH   | jeroreintegration        | 1.1.0             | JEROreIntegration-1.12.2-1.1.0.jar              | None                                     |
	| LCH   | journeymap               | 1.12.2-5.7.1      | journeymap-1.12.2-5.7.1.jar                     | None                                     |
	| LCH   | mcjtylib_ng              | 3.5.4             | mcjtylib-1.12-3.5.4.jar                         | None                                     |
	| LCH   | supermartijn642configlib | 1.0.9a            | supermartijn642configlib-1.0.9a-mc1.12.jar      | None                                     |
	| LCH   | supermartijn642corelib   | 1.0.16a           | supermartijn642corelib-1.0.16a-mc1.12.jar       | None                                     |
	| LCH   | movingelevators          | 1.3.4             | movingelevators-1.3.4-mc1.12.jar                | None                                     |
	| LCH   | multiblockstages         | 1.2.0             | multiblockstages-1.2.0.jar                      | None                                     |
	| LCH   | oreexcavation            | 1.4.150           | OreExcavation-1.4.150.jar                       | None                                     |
	| LCH   | oeintegration            | 2.3.4             | oeintegration-2.3.4.jar                         | None                                     |
	| LCH   | orestages                | 2.0.37            | OreStages-1.12.2-2.0.37.jar                     | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | pouchofunknown           | 1.9               | pouchofunknown-1.9.jar                          | None                                     |
	| LCH   | projecte                 | 1.12.2-PE1.4.1    | ProjectE-1.12.2-PE1.4.1.jar                     | None                                     |
	| LCH   | prospectors              | 1.0.2             | prospectors-1.0.2.jar                           | None                                     |
	| LCH   | reborncore               | 3.19.5            | RebornCore-1.12.2-3.19.5-universal.jar          | None                                     |
	| LCH   | refinedstorage           | 1.6.16            | refinedstorage-1.6.16.jar                       | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
	| LCH   | rebornstorage            | 1.0.0             | RebornStorage-1.12.2-3.3.4.1.jar                | None                                     |
	| LCH   | recipestages             | 1.1.3             | RecipeStages-1.1.3.8.jar                        | None                                     |
	| LCH   | refinedexchange          | 2.1.1             | refinedexchange-2.1.1.jar                       | None                                     |
	| LCH   | refinedstorageaddons     | 0.4.5             | refinedstorageaddons-0.4.5.jar                  | None                                     |
	| LCH   | refinedstoragerequestify | ${version}        | refinedstoragerequestify-1.12.2-1.0.2-3.jar     | None                                     |
	| LCH   | bq_rf                    | CI_MOD_VERSION    | RFExpansion-3.4.31.jar                          | None                                     |
	| LCH   | rslargepatterns          | 1.12.2-1.0.0.0    | RSLargePatterns-1.12.2-1.0.0.1.jar              | None                                     |
	| LCH   | oeshapeselector          | 1.0               | shapeselector-1.12.2b4.jar                      | None                                     |
	| LCH   | simpleoresamples         | 2.0               | SimpleOreSamples-1.12-2.0.jar                   | None                                     |
	| LCH   | bq_standard              | 3.4.173           | StandardExpansion-3.4.173.jar                   | None                                     |
	| LCH   | stevescarts              | 2.4.32.137        | StevesCarts-1.12.2-2.4.32.137.jar               | None                                     |
	| LCH   | tieredtooltips           | 1.0.4             | TieredTooltips-2.0.0.jar                        | None                                     |
	| LCH   | tinkerstages             | 2.0.15            | TinkerStages-1.12.2-2.0.15.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | wailaharvestability      | 1.1.12            | WailaHarvestability-mc1.12-1.1.12.jar           | None                                     |
	| LCH   | wailastages              | 2.0.23            | WailaStages-1.12.2-2.0.23.jar                   | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | worldselectionadvanced   | 1.12.2-02         | WorldSelectionAdvanced-1.12.2-02.jar            | None                                     |
	| LCH   | xnet                     | 1.8.2             | xnet-1.12-1.8.2.jar                             | None                                     |
	| LCH   | zenstages                | 0.5.0-null        | zenstages-0.5.0.jar                             | None                                     |
	| LCH   | kiwi                     | 0.5.3.32          | Kiwi-1.12.2-0.5.3.32.jar                        | None                                     |
	| LCH   | researchtable            | 1.0.2             | ResearchTable-1.0.2.jar                         | None                                     |
	| LCH   | adchimneys               | 1.12.2-3.5.15.0   | AdChimneys-1.12.2-3.5.15.0-build.0560.jar       | None                                     |
	| LCH   | adfinders                | 1.12.2-2.3.17.0   | AdFinders-1.12.2-2.3.17.0-build.0559.jar        | None                                     |
	| LCE   | osv                      | 5.14              | Ore Stone Variants-5.14.jar                     | None                                     |

**Comment by BraveCaperCat** [comment]
Mod version: Latest release(5.14)
Dependency version: Cat lib is NOT for 1.12.2
Forge version: 14.23.5.286
Minecraft version: 1.12.2

**Comment by BraveCaperCat** [comment]
DO NOT Close this issue because "I don't have enough info" Just ask me what you need

**Comment by BraveCaperCat** [comment]
I'm just trying to make a modpack

**Comment by PersonTheCat** [comment]
Are you sure this is the right log? This log indicates a crash due to Advanced Rocketry. 
```
[14:19:22] [Server thread/FATAL]: A serious error has occured while loading the planetDefs XML
[14:19:22] [Server thread/WARN]: Java has been asked to exit (code -1)
[14:19:22] [Server thread/WARN]: Exit trace:
[14:19:22] [Server thread/WARN]: 	zmaster587.advancedRocketry.dimension.DimensionManager.createAndLoadDimensions(DimensionManager.java:825)
[14:19:22] [Server thread/WARN]: 	zmaster587.advancedRocketry.AdvancedRocketry.serverStarting(AdvancedRocketry.java:1229)
```
Also, a fair warning: 5.14 is _not_ the latest version. It is 10 versions and 2 major updates out of date. The code is so different from what I'm working with now that it's quite difficult for me to analyze whenever things go wrong. I can provide assistance with using it, but truly supporting something this far out of date is not feasible.

**Comment by PersonTheCat** [comment]
Don't have enough info.

**Comment by BraveCaperCat** [comment]
5.14 is the latest release
otherwise curseforge would update it

**Comment by BraveCaperCat** [comment]
The crash only happened when this mod was installed

**Comment by BraveCaperCat** [comment]
It could be a mod compatibility issue with advanced rocketry, but this mod broke my game,

**Comment by BraveCaperCat** [comment]
> Don't have enough info.

I said to ask me what you need

**Comment by BraveCaperCat** [comment]
Here:
[AdvancedRocketry-1.12.2-1.7.0-232-universal.zip](https://github.com/PersonTheCat/OreStoneVariants/files/8239804/AdvancedRocketry-1.12.2-1.7.0-232-universal.zip)
 I uploaded it as .zip but you can just rename it in .jar format if you need.

**Comment by BraveCaperCat** [comment]
I'll work on something else in the meantime, while you fix the issue

**Comment by BraveCaperCat** [comment]
> A serious error has occured while loading the planetDefs XML

Opps, i should remove resetPlanetsFromXML = true
from advanced rocketry config

**Comment by PersonTheCat** [comment]
@BraveCaperCat I'm gonna offer you some personal advice. 

You will find people are friendlier and much more willing to help when you are patient. 

In the past few weeks, you have spammed and harassed me and several other developers in the modding community who I respect and care for very much. I do not appreciate this.

https://github.com/Iskallia/Vault-public-S1/issues/750
https://github.com/Advanced-Rocketry/AdvancedRocketry/issues/2295
https://github.com/Advanced-Rocketry/AdvancedRocketry/issues/2297
https://github.com/simibubi/Above-and-Beyond/issues/396

In the future, I hope you will consider:
* Posting one comment at a time
* Reusing existing threads instead of creating new ones
* Asking for help, not demanding it
* Asking for clarification before insisting that our code is broken
* Using the most descriptive and objective title you can, while still being concise

If you find that your threads are getting deleted, please do not be offended. This is just how JIRA boards work and is mostly the product of (Agile Methodology)[https://www.atlassian.com/agile]. Most developers are used to working in Agile environments and so that's how we treat our projects. Our goal is to be organized and objective because _that's how we get work done_.

Please understand that us developers are regular people just like you; we do have jobs, other things to do, and we are not getting paid for this very difficult work.

---

To answer your question, **I still need the correct log file**. The log you sent me does not indicate the crash in your description. 

Based on the error message you shared:
```
(The process cannot access the file because it is being used by another process)
```
This message means exactly what it says. If you don't know who's using the file, **it's probably your antivirus program**. To confirm, you can try:
* Disabling your antivirus program
* Rerunning the application
* Checking for `config/osv/resources.zip` -- it should exist and contain generated assets for every block

If these changes work, you can re-enable your antivirus software and simply continue using these generated assets. To be sure that OSV won't try to generate new assets--thus risking this error again--you can disable `generateResources` in the common config. 

---

Finally, you should understand that the behavior in question was replaced in OSV 6.0. OSV is now on version _7.0_. The new resource management behavior was both a massive change and simply not practical for OSV 1.12, a version which very few people are still using. For these reasons, **I will not backport the new behavior**. 

This software was written almost 4 years ago. I have only been patching this mod to fix **minor bugs** since that time as I work on newer versions and other projects. 

OSV 7.6 is a drastically different mod from 5.14. It was majorly expanded in 6.0 and completely rewritten--from scratch--for 7.0. These are two totally different mods and I can only truly support **one of them**. 

---

If you have any further **bugs** to report, please create a new issue. If you have more to add for this issue, please leave a **single comment**. If you have any questions regarding user setup and getting started with OSV, please use our (Discord server)[https://discord.gg/UNsXfvA] instead.
