### ISSUE TITLE
failed to load correctly please help

### ISSUE THREAD

**Issue by EnesBr0** [PersonTheCat/OreStoneVariants#157]
[crash-2022-03-20_17.59.20-fml.txt](https://github.com/PersonTheCat/OreStoneVariants/files/8311622/crash-2022-03-20_17.59.20-fml.txt)
it says:error copying file from the jar but i cant fix it.
orestonevariantsversion:6.2

**Comment by PersonTheCat** [comment]
Hey, just a heads up: 6.2 is not the latest version of the mod. 7.0 was a full rewrite and we're on 7.6 now, so this issue is not valid. Please update the mod first and try again.
