### ISSUE TITLE
Mod compatibility problem with Abnormals (1.16.5)

### ISSUE THREAD

**Issue by zanecek** [PersonTheCat/OreStoneVariants#158]
Vanila ores (even when they are turned off) are generated together with osv ores, but only in Abnormal's biomes.
I use 1.16.5: OSV 7.6, Abnormals Core 3.3.1 + a lot of Abnormal's mods.
https://www.curseforge.com/minecraft/mc-mods/blueprint

**Comment by PersonTheCat** [comment]
This honestly does not sound like a bug with OSV. I suspect that Abnormals is just manually overriding the generation settings for its own biomes, but I'm not sure yet. Don't see anything related in this repo. 

I'll take a better look at this in a couple days. 

In the meantime, is there anyway you run the `/osv debug features` command and look for anything that sounds like Abnormals ores? If so, you can just add that value in the common config and it'll turn them off.

**Comment by PersonTheCat** [comment]
I will be closing this issue, as I do not believe this is a bug with OSV. Feel free to reopen the issue, if needed.

**Comment by zanecek** [comment]
I solved the problem by adding mode Oreconfig, which suppresses the generation of all ores in all biomes well.
https://www.curseforge.com/minecraft/mc-mods/oreconfig
