### ISSUE TITLE
OSV Crash W/ Catlib (OSV- 7.6 and CatLib- 1.20) - Latest Versions [FORGE]

### ISSUE THREAD

**Issue by FalsifiedKing** [PersonTheCat/OreStoneVariants#160]
Image of the crash:

![ERROR](https://user-images.githubusercontent.com/83038473/161443020-9ae9d415-1970-4316-a1d7-9b5acf645658.PNG)

The report:

[latest.log](https://github.com/PersonTheCat/OreStoneVariants/files/8405248/latest.log)

(Weird thing, when I start my computer up and hop on it gives the error. However, when I log off and log back on it is gone and it loads fine. Again, when I get back on it shows the crash. It is like every other entry crashes and it makes no sense.)

**Comment by PersonTheCat** [comment]
Oh cool. This is a minor little bug with CatLib, actually. It's just trying to delete a folder from your backups, which Windows won't let you do unless the folder is empty. I'll fix it in a bit.

In the meantime, just delete this folder and let me know if that works: 
```
.minecraft/config/osv/backups
```

**Comment by FalsifiedKing** [comment]
Whelp. That was very odd. Before I did what you requested, I reinstalled it and that seemed to work. I feel so dumb, sorry for taking your time. However, if this issue arises again I will be sure to what you have said. Thank you for your help and thank you for the mod! 

:)

**Comment by PersonTheCat** [comment]
Yeah, no worries. This is a bug, however, and eventually will happen again, if you regenerate your files too many times. I'll still get it fixed.

**Comment by FalsifiedKing** [comment]
You are so kind, have a great day/night! :D

**Comment by FalsifiedKing** [comment]
Edit: Before I misread, I have completed your previous instruction with further detail. The issue IS NOT SOLVED when deleting the backups folder. When deleted the games makes a backup folder with assets. Then if you keep re-opening the game a new assets folder will appear. Once at asster folder (10), it will do this "every other" thing due to  an overload.

**Comment by PersonTheCat** [comment]
@FalsifiedKing Thanks! Had a rough week after this was closed and never uploaded fixes. Will take care of that soon

**Comment by FalsifiedKing** [comment]
No worries at all, take your time. It has been a rough couple of years. I hope things get better for you!

**Comment by PersonTheCat** [comment]
@FalsifiedKing [CatLib 1.21+1.16.5](https://www.curseforge.com/minecraft/mc-mods/catlib/files) fixes the backup truncation error where folders were not supported. Do you mind giving this a try and letting me know if it fixes the issue?

**Comment by PersonTheCat** [comment]
@FalsifiedKing Hey! Sorry, I didn't see your edit. Creating these folders is the expected behavior **whenever the resources are deleted and regenerated**. However, it should be able to delete those folders correctly now, regardless of their contents. If that isn't working, feel free to share some logs and I'll take another look this weekend.
