### ISSUE TITLE
Server-Crash with latest OSV and Catlib on Forge 1.16.5-36.2.34

### ISSUE THREAD

**Issue by DuraBrite** [PersonTheCat/OreStoneVariants#161]
**Mod-Version:** 7.6
**Forge-Version:** 1.16.5 - 36.2.34

**Issue:** After Updating Catlib to the latest Version (1.21+16 -- btw on CatLibs Mod Page Version is stated as 1.21+16 while filename and registered Version is 1.20+16), a newly setup server crashes on startup with:
`Attempted to load class net/minecraft/client/gui/screen/Screen for invalid dist DEDICATED_SERVER`

**Crash-Report:** [crash-2022-04-29_02.08.13-fml.txt](https://github.com/PersonTheCat/OreStoneVariants/files/8587397/crash-2022-04-29_02.08.13-fml.txt)

Client startup works fine.

**Comment by PersonTheCat** [comment]
Fixed in [CatLib 1.22+1.16](https://www.curseforge.com/minecraft/mc-mods/catlib/files/all).
