### ISSUE TITLE
[1.12.2 | Ease of Use Suggestion] Enable Vanilla Ores By Default

### ISSUE THREAD

**Issue by oxocutable** [PersonTheCat/OreStoneVariants#162]
Currently the mod is set to disable vanilla ores by default, making playing regular Minecraft near impossible.
This should be changed to true by default for ease of use or a notice should be placed on the mod's page.

**Comment by PersonTheCat** [comment]
Hey, thanks for pointing this out. I disagree with this being a good change for QOL, as it would defeat the purpose of the mod. When OSV disables world generation features, it replaces them with its own, and so coal ore and other vanilla-style ore veins still spawn out of the box.

**Comment by oxocutable** [comment]
I brought this up because vanilla veins like coal and iron don't spawn.
Perhaps this is a quirk of it running alongside Biomes O' Plenty?

**Comment by PersonTheCat** [comment]
Is this after any config changes at all?

**Comment by oxocutable** [comment]
I had a clean install of Biomes O' Plenty, Underground Biomes, and Ore Stone Variants.

The problem shouldn't be because of Underground Biomes, because UB typically fills the ore veins with standard Minecraft ores.

**Comment by PersonTheCat** [comment]
Ohhh that's what it is. There used to be an option in 1.12 to automatically ignore OSV ores if UBC was present, since that mod already adds them.

**Comment by oxocutable** [comment]
It is strange that no ores generate at all when both mods are installed, is it not?
