### ISSUE TITLE
[1.16] Setting the background block of an ore to a block with a different hardness than the base block (like quark's deepslate) allows that variant to be mined with any pickaxe

### ISSUE THREAD

**Issue by RecyclingTiger** [PersonTheCat/OreStoneVariants#163]
This ignores the forge harvest level. The reason I think this is a bug is because the block still takes a longer time to mine as if you were using the wrong tool. Other quark stones that have the same hardness as stone don't have this problem.

For example, if an ore needs a diamond pickaxe to mine and its base block is stone,
a andesite variant works correctly (doesn't drop) when mined with an iron pickaxe.
however a sandstone variant of the same ore can be mined with any pickaxe, although it takes longer to mine than normal sandstone when using iron or below.

**Comment by PersonTheCat** [comment]
This is not a bug and has to do with `bgImitation`, which can be disabled. The ores can be configured individually as well. But because sandstone is very soft, this makes sense as the default behavior.
