### ISSUE TITLE
A smattering across the board for support - Sunconure11

### ISSUE THREAD

**Issue by PersonTheCat** [PersonTheCat/OreStoneVariants#45]
This thread is moved from CurseForge. The original can be found at [this link.](https://minecraft.curseforge.com/projects/ore-stone-variants/issues/2)

**Sunconure11:**
> Would it be possible to add support for Embers, if it's ores are already not supported? 
>
> Furthermore, why not add ore variants for stones from Rustic + Earthworks + Chisel?
>
> Biomes O' Plenty has a few ores as well, albeit in the form of gemstones. Glass Hearts is the same deal for the most part.
>
> Astral Sorcery has a few ores, albeit they are fairly rare. Furthermore, it has it's own marble.
>
> Defiled Lands would also be interesting to add support for, if you could work it out, since it turns a few vanilla ores into special materials for usage within that mod.

**Comment by PersonTheCat** [comment]
Most original responses have been omitted. See the [original thread](https://minecraft.curseforge.com/projects/ore-stone-variants/issues/2) for records. Here's what has been implemented:
- Rustic 
- Earthworks
- Biomes O' Plenty
Here's what has not been implemented (10/17/18):
- Chisel (due to an issue with block models)
- Astral Sorcery
- Defiled Lands

**Comment by PersonTheCat** [comment]
**pupnewfster:**

> Other ones you may also want to think about adding:
> Modern Metal Support (Probably relatively easy given you have Base Metal Support)
NuclearCraft Support
>
> Two that may be interesting if relatively easy to add though may not be worth it given how small a subset of ores it would be:
> Actually Additions black quartz
>
> AE2 Certus Quartz and Charged Certus Quartz (may be harder with figuring out if it should be charged or not)

Here's what has been implemented:

- Modern Metals

Here's what has not (10/17/18):

- NuclearCraft
- Actually Additions
- AE2

**Comment by Handeril** [comment]
I look forward to any updates on this thread, as this all has reasonable significance...

**Comment by PersonTheCat** [comment]
@Handeril this is not something I can really provide for 1.12. Most of these mods can be supported through the presets, especially in 1.16 and 1.18. OSV 7.x can even generate the presets on the fly, so there's no need to manually create them or for me to implement support for them anymore.
