### ISSUE TITLE
[Request] [Enhancement] Pigmen Agro

### ISSUE THREAD

**Issue by Voxel-Friend** [PersonTheCat/OreStoneVariants#62]
I would love a config option so that if breaking custom ore generated in the nether, pigmen nearby would get aggro'd, similar to "Nether Ores." As a bonus, maybe endermen aggro for the end (less of a priority)?

**Comment by PersonTheCat** [comment]
Huh. I've never heard this idea. Sounds pretty neat and straightforward to implement. What conditions would trigger this, more specifically? Would ores be setup specifically to do that? Would it just be any ore that spawns in netherrack? Any ore in the Nether? Etc.

**Comment by Voxel-Friend** [comment]
If at all possible, having as much configuration as possible would be ideal. But at the very least ores found in netherrack aggro pigmen, and ores found in endstone aggro endermen.

**Comment by Voxel-Friend** [comment]
Modpack authors crave this level of configuration, and this would be a good way for hardcore packs to mess with players or to add difficulty.

**Comment by PersonTheCat** [comment]
As someone who was previously working on a modpack centered around exploring and finding new ores in the End, I think this sounds like an extremely cool idea. I can definitely add a per-ore override in the ore presets, and then possibly also a global setting to allow this either per-dimension or per background block. Again, though, I still plan on finishing the CaveGenerator rewrite before getting back into OSV. I'm hoping to be able to work on OSV in the next few weeks, but I can't say for sure how long it'll be.

**Comment by PersonTheCat** [comment]
As this issue was for 1.12, it will technically never be resolved. However, in later versions of the game, this is now handled by block tags and is implicitly supported by OSV. I'm marking this issue as resolved, but please reopen it if you're still interested.
