### ISSUE TITLE
[Thermal] Incomplete Compat

### ISSUE THREAD

**Issue by Dragnier** [PersonTheCat/OreStoneVariants#67]
Thermal also spawns oil and clathrates that are not currently supported by default in your mod. I am going to guess that this is because they spawn both flowing liquid and and an item when broken. Is there any way you can add compatibility for them though?

thermalfoundation:ore_fluid:0 - Oil Sand
thermalfoundation:ore_fluid:1 - Oil Shale (Gravel?)
thermalfoundation:ore_fluid:2 - Destabilized Redstone Ore (Stone)
thermalfoundation:ore_fluid:3 - Energized Netherrack
thermalfoundation:ore_fluid:4 - Resonant End Stone
thermalfoundation:ore_fluid:5 - Oil Red Sand

**Comment by PersonTheCat** [comment]
If I remember correctly, I didn't add these because of questions over how I should handle block models for fluid ores and how they would be different from their normal counterparts. Sorry for taking so long to get back to you on this one, but I'm just not sure how to proceed. :/

**Comment by PersonTheCat** [comment]
I will most likely never add support for custom fluid types in OSV, as I can't see how I would make additional variants or what purpose they would serve. Feel free to reopen this issue or create a PR if you're still interested.
