### ISSUE TITLE
Tryna make some ores glow

### ISSUE THREAD

**Issue by Goy288** [PersonTheCat/OreStoneVariants#77]
So as the title here suggest I'm trying to make some of the vanilla ores glow(particularly diamond,  redstone, and emerald) in the modpack I'm making using the [Connected Textures Mod](https://www.curseforge.com/minecraft/mc-mods/ctm) and the [Resource Loader](https://www.curseforge.com/minecraft/mc-mods/resource-loader) mod. 
The problem here, is that all of my attempts here seem to fall flat.
![Vanilla ores at the top, OSV ores at the bottom.](https://i.ibb.co/34L2k1B/2019-09-15-13-06-11.png)

How to make glowing ores with CTM is as follows.

Make a transparent overlay of just the [ore bits themselves](https://github.com/Chisel-Team/ConnectedTexturesPack/blob/master/assets/minecraft/textures/blocks/emerald_ore_glow.png).

Nextm make a special [.MCMETA file](https://github.com/Chisel-Team/ConnectedTexturesPack/blob/master/assets/minecraft/textures/blocks/emerald_ore_glow.png.mcmeta) to help set the glow level.

Replace the ore's [model file](https://github.com/Chisel-Team/ConnectedTexturesPack/blob/master/assets/minecraft/models/block/emerald_ore.json) to have the glowing overlay texture and make [util_cube_glow_2_all](https://github.com/Chisel-Team/ConnectedTexturesPack/blob/master/assets/minecraft/models/block/util_cube_glow_2_all.json) the parent.

.

Now obviously, this is a little bit of a problem when dealing with block models that are dynamically generated, so the only block model I had access to was [dynamic_block.json](https://pastebin.com/Ngd0R6gp).

I tried editing the model json to look like [this](https://pastebin.com/fx4V2Qnk), but that just ended up making the blocks invisible.

I also tried to remake the [file](https://pastebin.com/Hgt6M6DZ) in a similar style to [util_cube_glow_2](https://github.com/Chisel-Team/ConnectedTexturesPack/blob/master/assets/minecraft/models/block/util_cube_glow_2.json), but that just did absolutely nothing.

I think what possibly might be the problem, is that I made multiple .MCMETA files for the dynamically generated ore cutouts made by Ore Stone Variants to be loaded by the resource loader, but resources.zip gets loaded and takes a higher priority.

Assuming that this is true, is it possible to lower the priority of resources.zip?
And assuming that I'm completely wrong about that as well, and there's nothing I can do, could you please consider adding special compatibility with CTM to add an option to implement glowing ores?

**Comment by PersonTheCat** [comment]
This is actually handled by `Block#gerLightLevel`. OSV has a feature built in for this. You have to create custom OreProperties jsons for it, which I realize is a bit tedious at the moment, but it can be done.

**Comment by Goy288** [comment]
Alright, I'll see what I can do with that.
Thank you very much for this information, and I'll get back to you on this later to inform you of whether or not i was successful.

**Comment by Goy288** [comment]
Alright, so I've made three zip files, "diamond_ore", "emerald_ore", and "redstone_ore" respectively, and I've added these in each JsonProperties.json, with x being each one's respective light level.
```
{
	"lightLevel": x
}
```
Unfortunately, this failed to do anything whatsoever, but then after looking through your comment I considered that you might have actually meant to type OreProperties.json instead of JsonProperties.json.

After renaming each one to OreProperties.json, I decided to try again, but unfortunately was graced with this [crash log](https://pastebin.com/yM7S7XbL).

The main excerpt from the aforementioned crash log says that the texture for emerald ore is missing.
```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Ore Stone Variants (ore_stone_variants)
Caused by: java.lang.RuntimeException: Error: A texture for emerald_ore is invalid. Path: null does not exist.
```
I have considered that I need to fill the OreProperties.json files with more descriptive information. Is this true, or is this some other issue entirely?

**Comment by Goy288** [comment]
Alright, I have filled the OreProperties.json in diamond_ore and emerald_ore with the necessary information(I got rid of redstone since I didn't know how to replicate it's glow-on-touch properties), and while the ores "glow", I think we might have had a miscommunication on what I meant by that.

You see, the "glowing" effect I'm trying to add is a purely cosmetic addition that is supposed to make the ore bits embedded into the stone pop out, like how you might see a glint coming off of a precious gemstone, or the natural glow of redstone.

The "lightLevel" value doesn't exactly do this, and instead turns the ores into an active light source, like a glowstone block or a torch.

**Comment by PersonTheCat** [comment]
Hmm. I see. You might be referring to the shade feature used by some block models. Check the config file for "overlays are shaded" and set it to false. Let me know if that's what you were thinking.

**Comment by Goy288** [comment]
I already set that to false, but I now decided to add the ores I wanted to glow to the "Shade Overrides" list, an it _almost_ works.

The ore overlay seems to glow in the menu selection, to the point where you can no longer distinguish them from each other by their looks alone.
![OSV ores on the right, vanilla ores on the left](https://i.ibb.co/JdBWCfz/image.png)
But when it comes to actually viewing the ores ingame, they look almost exactly the same as they did before.
The reason why I said "almost" is if you turn on night vision, you see that the ore bits are now just as, if not brighter, then the vanilla ore bits.
![OSV ores on the bottom, vanilla ores on the top](https://i.ibb.co/y4HRdzk/2019-09-17-20-49-10.png)
I honestly think I may give up at this point, the only other option I can think of is to edit the models and the blockstates to manually assign textures and backgrounds to each ore.

I'll get back to you later, and assuming I'm successful, share some of the files for people who also want their ores to glow.

**Comment by Goy288** [comment]
Yeah, changing the block model seems do nothing. 

What I tried to do was make a new JSON file in `ore_stone_variants\blockstates` and calling it [`diamond_ore.json`](https://pastebin.com/qNCkxWxX). 

While I do seem to be able to manipulate the blockmodel to some degree, I appear to be unable to manipulate whether or not the ore glows for some reason. For now, I'm just gonna give up.

**Comment by PersonTheCat** [comment]
Sorry you didn't find what you were looking for...

**Comment by Goy288** [comment]
It's quite alright. It wouldn't really change the gameplay much anyway.

**Comment by PersonTheCat** [comment]
Since this issue was for 1.12 (?), it will technically never be resolved. However, as of OSV 7.0+, the mod does now support emissive rendering. Marking this issue as resolved.
