### ISSUE TITLE
Breaking animation doesn't play on any ores.

### ISSUE THREAD

**Issue by Asmidus** [PersonTheCat/OreStoneVariants#79]
The cracking animation doesn't show up on any of the ores generated. If you place the block after mining it, it will then show up but never the first time you mine it. This could be a conflict with some other mod. This is reproduceable by just installing the Crucial modpack and mining any kind of ore.

**Comment by Asmidus** [comment]
After a little trial and error I've confirmed that it's an issue with optifine. Using any kind of shaders (internal or custom) and this mod will produce this behavior.

**Comment by PersonTheCat** [comment]
This has to do with how transparent blocks are rendered with most shader packs. The blocks render transparently so that each layer of textures can be neatly blended together, but it can be disabled in the config file. Look for "enable transparency," I believe.

**Comment by Asmidus** [comment]
Changing that option did not fix the issue

**Comment by Metadorius** [comment]
Having the same issue. Optifine F5, latest Sildur's Enhanced Default shaders. Option doesn't affect the issue.

**Comment by PersonTheCat** [comment]
Since this issue was for 1.12, it technically will never be fixed. However, starting with OSV 7.0, the mod now uses a single layer model by default which does not have this issue. Marking this ticket as resolved.
